FROM python:3.11-slim

LABEL org.opencontainers.image.title="Secure Prompt Sanitizer Backend"
LABEL org.opencontainers.image.description="FastAPI backend for Secure Prompt Sanitizer"
LABEL org.opencontainers.image.source="https://github.com/AminJSyed/secure-prompt-sanitizer"
LABEL org.opencontainers.image.licenses="MIT"


WORKDIR /app

RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend ./backend
COPY rules ./rules

EXPOSE 8000

CMD ["uvicorn", "backend.api:app", "--host", "0.0.0.0", "--port", "8000"]
